// @ts-ignore - Deno runtime
import { createClient } from 'npm:@supabase/supabase-js@2.39.3';
import { resolveKkOpsAuthorization, restrictRequestedStores } from '../_shared/authorization.ts';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const response=(body:unknown,status=200,correlationId?:string)=>new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json',...(correlationId?{'x-correlation-id':correlationId}:{})}});
const validDate=(v:unknown)=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(Date.parse(`${v}T12:00:00Z`));
Deno.serve(async(req)=>{const started=performance.now(),correlationId=req.headers.get('x-correlation-id')||crypto.randomUUID();let stage='request',context:any={correlationId};const fail=(status:number,code:string,message:string,error?:unknown)=>{console.error('[article-analysis]',{...context,stage,status,code,durationMs:Math.round(performance.now()-started),error:error instanceof Error?error.message:undefined});return response({ok:false,code,message,stage,correlationId},status,correlationId)};
  if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return fail(405,'METHOD_NOT_ALLOWED','Méthode non autorisée.');
  try{stage='authentication';const auth=req.headers.get('Authorization');if(!auth)return fail(401,'UNAUTHORIZED','Session requise.');
    const url=Deno.env.get('SUPABASE_URL'),key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!url||!key)return fail(500,'CONFIGURATION_ERROR','Configuration serveur incomplète.');
    const db=createClient(url,key,{auth:{autoRefreshToken:false,persistSession:false}});const token=auth.replace(/^Bearer\s+/i,'');const {data:{user},error:userError}=await db.auth.getUser(token);if(userError||!user)return fail(401,'UNAUTHORIZED','Session invalide ou expirée.',userError);
    stage='authorization';const {data:roleRow,error:roleError}=await db.from('user_roles').select('role,store_ids').eq('user_id',user.id).maybeSingle();if(roleError)return fail(503,'DATABASE_ERROR','Impossible de vérifier les autorisations du compte.',roleError);const authorization=resolveKkOpsAuthorization(roleRow,user),role=authorization.role,assignedStoreIds=authorization.storeIds;context={...context,userId:user.id,email:user.email,role,roleSource:authorization.roleSource,assignedStoreCount:assignedStoreIds.length};if(!role)return fail(403,'FORBIDDEN','Votre rôle ne permet pas de consulter cette analyse.');
    stage='parameters';let body:any;try{body=await req.json()}catch(error){return fail(400,'INVALID_PARAMETERS','Corps JSON invalide.',error)};
    if(body.action==='search'){const q=String(body.query||'').trim();context={...context,action:'search',queryLength:q.length};if(q.length<2)return response([],200,correlationId);const pattern=`%${q.replace(/[%_]/g,'')}%`;stage='article-search';const results=await Promise.all([db.from('donut_varieties').select('id,name').ilike('name',pattern).limit(15),db.from('box_configurations').select('id,name').ilike('name',pattern).limit(15),db.from('production_items').select('variety_id,variety_name').ilike('variety_name',pattern).limit(50),db.from('box_productions').select('box_id,box_name').ilike('box_name',pattern).limit(50)]);const firstError=results.find(r=>r.error)?.error;if(firstError)return fail(503,'DATABASE_ERROR','La recherche des articles a échoué.',firstError);const [activeV,activeB,histV,histB]=results.map(r=>r.data||[]),map=new Map<string,any>();for(const row of activeV)map.set(`variety:${row.id}`,{id:row.id,name:row.name,type:'variety'});for(const row of activeB)map.set(`box:${row.id}`,{id:row.id,name:row.name,type:'box'});for(const row of histV)if(!map.has(`variety:${row.variety_id}`))map.set(`variety:${row.variety_id}`,{id:row.variety_id,name:row.variety_name,type:'variety',historical:true});for(const row of histB)if(!map.has(`box:${row.box_id}`))map.set(`box:${row.box_id}`,{id:row.box_id,name:row.box_name,type:'box',historical:true});console.log('[article-analysis]',{...context,stage:'complete',count:map.size,durationMs:Math.round(performance.now()-started)});return response([...map.values()].slice(0,30),200,correlationId)}
    const {productType,productId,startDate,endDate}=body,requestedStoreIds=Array.isArray(body.storeIds)?body.storeIds.filter((v:any)=>typeof v==='string'&&v):[];const storeIds=restrictRequestedStores(role,assignedStoreIds,requestedStoreIds);if(role==='store'&&!assignedStoreIds.length)return fail(403,'FORBIDDEN','Aucun magasin n’est associé à votre compte.');if(role==='store'&&!storeIds.length)return fail(403,'FORBIDDEN','Vous n’êtes pas autorisé à consulter les magasins demandés.');context={...context,action:'load',productType,productId,startDate,endDate,requestedStoreCount:requestedStoreIds.length,storeCount:storeIds.length,allStores:requestedStoreIds.length===0&&role!=='store'};if(!['variety','box'].includes(productType)||typeof productId!=='string'||!productId||!validDate(startDate)||!validDate(endDate)||startDate>endDate)return fail(400,'INVALID_PARAMETERS','Type, article ou période invalide.');
    stage='production-plans';const {data:plans,error:plansError}=await db.from('production_plans').select('id,date').gte('date',startDate).lte('date',endDate).order('date');if(plansError)return fail(plansError.code==='57014'?504:503,plansError.code==='57014'?'TIMEOUT':'DATABASE_ERROR','Impossible de charger les plans de production.',plansError);if(!plans?.length)return response({plans:[],total:0,correlationId},200,correlationId);
    stage='store-productions';const stores:any[]=[];for(let offset=0;offset<plans.length;offset+=100){let query=db.from('store_productions').select('id,plan_id,store_id,store_name,delivery_confirmed,waste_reported,deliverydate,delivery_date').in('plan_id',plans.slice(offset,offset+100).map(p=>p.id));if(storeIds.length)query=query.in('store_id',storeIds);const {data,error}=await query;if(error)return fail(error.code==='57014'?504:503,error.code==='57014'?'TIMEOUT':'DATABASE_ERROR','Impossible de charger les magasins.',error);stores.push(...(data||[]))}if(!stores.length)return response({plans:[],total:0,correlationId},200,correlationId);
    stage=productType==='box'?'box-productions':'production-items';const table=productType==='box'?'box_productions':'production_items',idColumn=productType==='box'?'box_id':'variety_id',items:any[]=[];for(let offset=0;offset<stores.length;offset+=100)for(let page=0;;page++){const {data,error}=await db.from(table).select('*').in('store_production_id',stores.slice(offset,offset+100).map(s=>s.id)).eq(idColumn,productId).order('id').range(page*500,page*500+499);if(error)return fail(error.code==='57014'?504:503,error.code==='57014'?'TIMEOUT':'DATABASE_ERROR',`Impossible de charger ${productType==='box'?'les boîtes':'les variétés'}.`,error);items.push(...(data||[]));if(!data||data.length<500)break}
    const byStore=new Map<string,any[]>();for(const item of items)byStore.set(item.store_production_id,[...(byStore.get(item.store_production_id)||[]),item]);const storesByPlan=new Map<string,any[]>();for(const store of stores){const rows=byStore.get(store.id);if(!rows?.length)continue;const entry={...store,production_items:productType==='variety'?rows:[],box_productions:productType==='box'?rows:[]};storesByPlan.set(store.plan_id,[...(storesByPlan.get(store.plan_id)||[]),entry])}const result=plans.map(p=>({...p,stores:storesByPlan.get(p.id)||[]})).filter(p=>p.stores.length);console.log('[article-analysis]',{...context,stage:'complete',rows:items.length,plans:result.length,durationMs:Math.round(performance.now()-started)});return response({plans:result,total:items.length,correlationId},200,correlationId);
  }catch(error){return fail(500,'INTERNAL_ERROR','Erreur interne lors de l’analyse article.',error)}});
