import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

export const PDF_COLORS = { green:[0,105,62], green2:[39,139,89], red:[190,30,45], ink:[22,35,29], muted:[96,108,102], paper:[246,249,247], line:[218,227,222], white:[255,255,255], amber:[173,104,0] } as const;
export const PDF_MARGIN = 15;
export const PDF_FOOTER = 13;
type RGB = readonly [number,number,number];
export interface PdfImage { data: string; width: number; height: number }
const color=(doc:jsPDF,kind:'text'|'fill'|'draw',rgb:RGB)=>kind==='text'?doc.setTextColor(...rgb):kind==='fill'?doc.setFillColor(...rgb):doc.setDrawColor(...rgb);
export const formatPdfNumber=(value:number|null|undefined)=>value==null?'—':new Intl.NumberFormat('fr-CH',{maximumFractionDigits:1}).format(value);
export const formatPdfPercent=(value:number|null|undefined)=>value==null?'—':new Intl.NumberFormat('fr-CH',{style:'percent',maximumFractionDigits:1}).format(value);
export const formatWritableValue=(value:number|null|undefined)=>value==null?'':formatPdfNumber(value);
export const formatPdfDate=(value:string)=>new Intl.DateTimeFormat('fr-CH',{day:'2-digit',month:'2-digit',year:'numeric',timeZone:'UTC'}).format(new Date(`${value.slice(0,10)}T12:00:00Z`));
export const safePdfFilename=(parts:string[])=>`${parts.join('_').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9_-]+/g,'-').replace(/-+/g,'-')}.pdf`;
export const createPdf=(orientation:'portrait'|'landscape'='portrait',meta:{title:string;subject?:string})=>{ const doc=new jsPDF({orientation,unit:'mm',format:'a4',compress:true}); doc.setProperties({title:meta.title,author:'KK OPS',subject:meta.subject||meta.title,keywords:'KK OPS, Krispy Kreme, opérations, rapport',creator:'KK OPS'}); return doc; };
export const ensurePageSpace=(doc:jsPDF,y:number,height:number,header?:()=>number)=>{ const limit=doc.internal.pageSize.getHeight()-PDF_FOOTER-8; if(y+height<=limit)return y; doc.addPage(); return header?header():PDF_MARGIN; };
export const addContainedImage=(doc:jsPDF,image:PdfImage|null|undefined,x:number,y:number,maxWidth:number,maxHeight:number)=>{if(!image||image.width<=0||image.height<=0)return false;const scale=Math.min(maxWidth/image.width,maxHeight/image.height);const width=image.width*scale,height=image.height*scale;try{doc.addImage(image.data,'PNG',x+(maxWidth-width)/2,y+(maxHeight-height)/2,width,height,undefined,'FAST');return true;}catch{return false;}};
export const addDocumentHeader=(doc:jsPDF,opts:{title:string;subtitle?:string;period?:string;scope?:string;logo?:PdfImage|null})=>{ const width=doc.internal.pageSize.getWidth();doc.setCharSpace(0);color(doc,'fill',PDF_COLORS.green);doc.rect(0,0,width,4,'F');const logoDrawn=addContainedImage(doc,opts.logo,PDF_MARGIN,7,30,11);if(!logoDrawn){color(doc,'text',PDF_COLORS.green);doc.setFont('helvetica','bold');doc.setFontSize(8.5);doc.text('KRISPY KREME / KK OPS',PDF_MARGIN,13);}color(doc,'text',PDF_COLORS.ink);doc.setFontSize(18);doc.text(opts.title,PDF_MARGIN,27);if(opts.subtitle){doc.setFont('helvetica','normal');doc.setFontSize(9);color(doc,'text',PDF_COLORS.muted);doc.text(opts.subtitle,PDF_MARGIN,33);} const info=[opts.period&&`Période : ${opts.period}`,opts.scope&&`Périmètre : ${opts.scope}`].filter(Boolean) as string[];doc.setFontSize(8);info.forEach((line,i)=>doc.text(line,width-PDF_MARGIN,11+i*5,{align:'right'}));color(doc,'draw',PDF_COLORS.line);doc.line(PDF_MARGIN,38,width-PDF_MARGIN,38);return 44;};
export const addSectionTitle=(doc:jsPDF,title:string,y:number,kicker?:string)=>{ if(kicker){doc.setFontSize(7);doc.setFont('helvetica','bold');color(doc,'text',PDF_COLORS.green2);doc.text(kicker.toUpperCase(),PDF_MARGIN,y);}doc.setFontSize(14);doc.setFont('helvetica','bold');color(doc,'text',PDF_COLORS.ink);doc.text(title,PDF_MARGIN,y+(kicker?6:0));return y+(kicker?12:7);};
export const addKpiCard=(doc:jsPDF,opts:{x:number;y:number;width:number;label:string;value:string;detail?:string;tone?:RGB})=>{color(doc,'fill',PDF_COLORS.paper);color(doc,'draw',PDF_COLORS.line);doc.roundedRect(opts.x,opts.y,opts.width,25,3,3,'FD');color(doc,'fill',opts.tone||PDF_COLORS.green);doc.roundedRect(opts.x,opts.y,2,25,1,1,'F');doc.setFont('helvetica','bold');doc.setFontSize(7);color(doc,'text',PDF_COLORS.muted);doc.text(opts.label.toUpperCase(),opts.x+6,opts.y+7);doc.setFontSize(15);color(doc,'text',PDF_COLORS.ink);doc.text(opts.value,opts.x+6,opts.y+16);if(opts.detail){doc.setFont('helvetica','normal');doc.setFontSize(6.5);color(doc,'text',PDF_COLORS.muted);doc.text(opts.detail,opts.x+6,opts.y+21);}};
export const addStatusBadge=(doc:jsPDF,status:string,x:number,y:number)=>{ const danger=status.includes('retrait'), up=status.includes('augmenter');const tone=danger?PDF_COLORS.red:up?PDF_COLORS.green:status.includes('réduire')?PDF_COLORS.amber:PDF_COLORS.muted;color(doc,'fill',tone);doc.roundedRect(x,y-4,Math.max(24,status.length*1.75+7),7,3,3,'F');color(doc,'text',PDF_COLORS.white);doc.setFont('helvetica','bold');doc.setFontSize(6.5);doc.text(status,x+3,y+.5);};
export const addDataTable=(doc:jsPDF,opts:{y:number;head:string[][];body:(string|number)[][];columnStyles?:Record<number,unknown>;compact?:boolean})=>{doc.setCharSpace(0);(doc as any).autoTable({startY:opts.y,head:opts.head,body:opts.body,tableWidth:opts.columnStyles?'wrap':doc.internal.pageSize.getWidth()-PDF_MARGIN*2,margin:{left:PDF_MARGIN,right:PDF_MARGIN,bottom:PDF_FOOTER+5},theme:'plain',showHead:'everyPage',rowPageBreak:'avoid',styles:{font:'helvetica',fontSize:opts.compact?8:8.2,cellPadding:opts.compact?1.35:2.1,textColor:PDF_COLORS.ink,lineColor:PDF_COLORS.line,lineWidth:.15,overflow:'linebreak',valign:'middle',minCellHeight:opts.compact?5.4:6.5},headStyles:{fillColor:PDF_COLORS.green,textColor:PDF_COLORS.white,fontStyle:'bold',fontSize:opts.compact?7.7:8,cellPadding:opts.compact?1.5:2},alternateRowStyles:{fillColor:PDF_COLORS.paper},columnStyles:opts.columnStyles||{}});return (doc as any).lastAutoTable.finalY as number;};
export const addDocumentFooters=(doc:jsPDF,opts:{documentName:string;period:string;generatedAt?:Date})=>{const pages=doc.getNumberOfPages(),generated=opts.generatedAt||new Date();for(let page=1;page<=pages;page++){doc.setPage(page);doc.setCharSpace(0);const width=doc.internal.pageSize.getWidth(),height=doc.internal.pageSize.getHeight();color(doc,'draw',PDF_COLORS.line);doc.line(PDF_MARGIN,height-PDF_FOOTER,width-PDF_MARGIN,height-PDF_FOOTER);doc.setFont('helvetica','normal');doc.setFontSize(7.2);color(doc,'text',PDF_COLORS.muted);doc.text(`KK OPS - ${opts.documentName} - Document interne et confidentiel`,PDF_MARGIN,height-7);doc.text(`${opts.period} | ${generated.toLocaleDateString('fr-CH')} | Page ${page} sur ${pages}`,width-PDF_MARGIN,height-7,{align:'right'});}};
export const addEmptyMessage=(doc:jsPDF,message:string,y:number)=>{color(doc,'fill',PDF_COLORS.paper);doc.roundedRect(PDF_MARGIN,y,doc.internal.pageSize.getWidth()-PDF_MARGIN*2,20,3,3,'F');doc.setFontSize(9);color(doc,'text',PDF_COLORS.muted);doc.text(message,PDF_MARGIN+6,y+12);return y+26;};
export const loadPdfImage=async(url:string):Promise<PdfImage|null>=>{try{const response=await fetch(url);if(!response.ok)return null;const blob=await response.blob();const data=await new Promise<string|null>(resolve=>{const reader=new FileReader();reader.onload=()=>resolve(typeof reader.result==='string'?reader.result:null);reader.onerror=()=>resolve(null);reader.readAsDataURL(blob);});if(!data)return null;const dimensions=await new Promise<{width:number;height:number}|null>(resolve=>{const image=new Image();image.onload=()=>resolve({width:image.naturalWidth,height:image.naturalHeight});image.onerror=()=>resolve(null);image.src=data;});return dimensions?{data,...dimensions}:null;}catch{return null;}};
