import type { AnalyticsObservation, ProductMetrics } from '../analytics/types.ts';
import { addDataTable, addDocumentFooters, addDocumentHeader, addEmptyMessage, addKpiCard, addSectionTitle, createPdf, ensurePageSpace, formatPdfNumber, formatPdfPercent, safePdfFilename, PDF_COLORS, PDF_MARGIN } from './pdfKit.ts';

export interface ReportContext { periodStart:string;periodEnd:string;scope:string;logo?:string|null;generatedAt?:Date }
const period=(ctx:ReportContext)=>`${ctx.periodStart} — ${ctx.periodEnd}`;
const validSalesRows=(observations:AnalyticsObservation[])=>observations.filter(o=>o.quality==='valid');

export const buildSalesPdf=(observations:AnalyticsObservation[],ctx:ReportContext,storeName?:string)=>{
  const doc=createPdf('landscape',{title:storeName?`Rapport de ventes — ${storeName}`:'Rapport de ventes',subject:'Ventes et déchets confirmés'});
  let y=addDocumentHeader(doc,{title:storeName?'Rapport magasin':'Rapport de ventes et déchets',subtitle:'Ventes confirmées et qualité opérationnelle',period:period(ctx),scope:storeName||ctx.scope,logo:ctx.logo});
  const rows=validSalesRows(observations).filter(o=>!storeName||o.storeName===storeName);
  const received=rows.reduce((s,o)=>s+o.received!,0),sold=rows.reduce((s,o)=>s+o.sold!,0),waste=rows.reduce((s,o)=>s+o.waste!,0);
  const width=(doc.internal.pageSize.getWidth()-PDF_MARGIN*2-9)/4;
  [['REÇU',formatPdfNumber(received)],['VENDU',formatPdfNumber(sold)],['DÉCHETS',formatPdfNumber(waste)],['TAUX DE DÉCHETS',formatPdfPercent(received?waste/received:0)]].forEach(([label,value],i)=>addKpiCard(doc,{x:PDF_MARGIN+i*(width+3),y,width,label,value})); y+=34;
  y=addSectionTitle(doc,'Détail des observations',y,'Données confirmées');
  if(rows.length)y=addDataTable(doc,{y,head:[['Date','Magasin','Produit','Type','Reçu','Vendu','Déchets','Taux déchets']],body:rows.map(o=>[o.salesDate,o.storeName,o.productName,o.productType==='box'?'Boîte':'Individuel',formatPdfNumber(o.received),formatPdfNumber(o.sold),formatPdfNumber(o.waste),formatPdfPercent(o.received?o.waste!/o.received:0)]),columnStyles:{4:{halign:'right'},5:{halign:'right'},6:{halign:'right'},7:{halign:'right'}}});else y=addEmptyMessage(doc,'Aucune observation confirmée pour ce périmètre.',y);
  addDocumentFooters(doc,{documentName:storeName?'Rapport magasin':'Rapport de ventes',period:period(ctx),generatedAt:ctx.generatedAt});
  return {doc,filename:safePdfFilename(['KKOPS',storeName?'Rapport-magasin':'Rapport-ventes',storeName||ctx.scope,ctx.periodStart,ctx.periodEnd])};
};

const statusOrder=['Retrait recommandé','Candidat au retrait','À réduire','À augmenter','À surveiller','À tester','À maintenir'];
export const buildDecisionPdf=(metrics:ProductMetrics[],ctx:ReportContext)=>{
  const doc=createPdf('landscape',{title:'Rapport d’aide à la décision',subject:'Performance des produits par point de vente'}),generated=ctx.generatedAt||new Date();
  const pageW=doc.internal.pageSize.getWidth(),pageH=doc.internal.pageSize.getHeight();
  doc.setFillColor(...PDF_COLORS.green);doc.rect(0,0,pageW,pageH,'F');doc.setFillColor(...PDF_COLORS.white);doc.roundedRect(18,22,pageW-36,pageH-44,5,5,'F');let coverLogo=false;if(ctx.logo){try{doc.addImage(ctx.logo,'PNG',30,34,42,16,undefined,'FAST');coverLogo=true;}catch{coverLogo=false;}}doc.setTextColor(...PDF_COLORS.green);doc.setFont('helvetica','bold');doc.setFontSize(10);if(!coverLogo)doc.text('KRISPY KREME  /  KK OPS',30,44);doc.setTextColor(...PDF_COLORS.ink);doc.setFontSize(30);doc.text('Rapport d’aide à la décision',30,72);doc.setFont('helvetica','normal');doc.setFontSize(15);doc.text('Performance des produits par point de vente',30,84);doc.setDrawColor(...PDF_COLORS.line);doc.line(30,99,pageW-30,99);doc.setFontSize(10);doc.text(`Période analysée   ${period(ctx)}`,30,115);doc.text(`Périmètre   ${ctx.scope}`,30,125);doc.text(`Généré le   ${generated.toLocaleString('fr-CH')}`,30,135);doc.setTextColor(...PDF_COLORS.red);doc.setFont('helvetica','bold');doc.text('DOCUMENT INTERNE ET CONFIDENTIEL — DIFFUSION CONTRÔLÉE',30,pageH-38);
  doc.addPage();let y=addDocumentHeader(doc,{title:'Résumé exécutif',subtitle:'Indicateurs consolidés du périmètre sélectionné',period:period(ctx),scope:ctx.scope,logo:ctx.logo});
  const received=metrics.reduce((s,m)=>s+m.received,0),sold=metrics.reduce((s,m)=>s+m.sold,0),waste=metrics.reduce((s,m)=>s+m.waste,0),valid=metrics.reduce((s,m)=>s+m.validCount,0),incomplete=metrics.reduce((s,m)=>s+m.incompleteCount+m.excludedCount+m.invalidCount,0);
  const cards=[['VENTES RÉELLES',formatPdfNumber(sold)],['QUANTITÉ REÇUE',formatPdfNumber(received)],['DÉCHETS',formatPdfNumber(waste)],['TAUX DÉCHETS',formatPdfPercent(received?waste/received:0)],['MAGASINS',String(new Set(metrics.map(m=>m.storeId)).size)],['PRODUITS',String(metrics.length)],['OBSERVATIONS VALIDES',String(valid)],['COMPLÉTUDE',formatPdfPercent(valid+incomplete?valid/(valid+incomplete):0)]];const cw=(pageW-PDF_MARGIN*2-9)/4;cards.forEach(([label,value],i)=>addKpiCard(doc,{x:PDF_MARGIN+(i%4)*(cw+3),y:y+Math.floor(i/4)*30,width:cw,label,value}));y+=68;
  y=addSectionTitle(doc,'Actions prioritaires',y,'Décisions recommandées');const actions=[...metrics].filter(m=>m.status!=='À maintenir').sort((a,b)=>statusOrder.indexOf(a.status)-statusOrder.indexOf(b.status));
  if(actions.length)addDataTable(doc,{y,head:[['Magasin','Produit','Type','Statut','Actuel → recommandé','Vente','Déchets','Occ.','Confiance','Explication']],body:actions.map(m=>[m.storeName,m.productName,m.productType==='box'?'Boîte':'Individuel',m.status,`${formatPdfNumber(m.referenceQuantity)} → ${m.recommendationLabel}`,formatPdfPercent(m.salesRate),formatPdfPercent(m.wasteRate),m.validCount,`${m.confidenceLevel} ${m.confidenceScore}/100`,m.reasons[0]||'—']),columnStyles:{4:{halign:'right'},5:{halign:'right'},6:{halign:'right'},7:{halign:'right'}}});else addEmptyMessage(doc,'Aucune action prioritaire sur la période.',y);
  for(const storeName of [...new Set(metrics.map(m=>m.storeName))].sort()){doc.addPage();y=addDocumentHeader(doc,{title:storeName,subtitle:'Analyse détaillée par produit',period:period(ctx),scope:storeName,logo:ctx.logo});const rows=metrics.filter(m=>m.storeName===storeName);const r=rows.reduce((s,m)=>s+m.received,0),v=rows.reduce((s,m)=>s+m.sold,0),d=rows.reduce((s,m)=>s+m.waste,0);[['VENDU',formatPdfNumber(v)],['REÇU',formatPdfNumber(r)],['DÉCHETS',formatPdfNumber(d)],['TAUX DÉCHETS',formatPdfPercent(r?d/r:0)]].forEach(([label,value],i)=>addKpiCard(doc,{x:PDF_MARGIN+i*(cw+3),y,width:cw,label,value}));y+=34;y=addSectionTitle(doc,'Produits et recommandations',y);addDataTable(doc,{y,head:[['Produit','Type','Reçu','Vendu','Déchets','Vente','Déchets %','Rupt.','Tendance','Actuel','Recommandé','Confiance','Statut']],body:rows.map(m=>[m.productName,m.productType==='box'?'Boîte':'Individuel',m.received,m.sold,m.waste,formatPdfPercent(m.salesRate),formatPdfPercent(m.wasteRate),`${m.probableStockouts}/${m.validCount}`,m.trend==null?'—':formatPdfPercent(m.trend),formatPdfNumber(m.referenceQuantity),m.recommendationLabel,`${m.confidenceLevel} ${m.confidenceScore}`,m.status]),columnStyles:{2:{halign:'right'},3:{halign:'right'},4:{halign:'right'},5:{halign:'right'},6:{halign:'right'}}});}
  doc.addPage();y=addDocumentHeader(doc,{title:'Lecture transversale par produit',subtitle:'Les écarts entre magasins sont des signaux à examiner, pas des causalités démontrées.',period:period(ctx),scope:ctx.scope,logo:ctx.logo});const products=new Map<string,ProductMetrics[]>();metrics.forEach(m=>products.set(`${m.productType}:${m.productId}`,[...(products.get(`${m.productType}:${m.productId}`)||[]),m]));addDataTable(doc,{y,head:[['Produit','Type','Magasins','Meilleur taux','Plus faible taux','Lecture']],body:[...products.values()].map(rows=>{const rates=rows.map(r=>r.salesRate);return[rows[0].productName,rows[0].productType==='box'?'Boîte':'Individuel',rows.length,formatPdfPercent(Math.max(...rates)),formatPdfPercent(Math.min(...rates)),Math.max(...rates)-Math.min(...rates)>.25?'Résultats contrastés selon les magasins':'Performance relativement homogène'];})});
  doc.addPage();y=addDocumentHeader(doc,{title:'Qualité des données et méthodologie',period:period(ctx),scope:ctx.scope,logo:ctx.logo});y=addSectionTitle(doc,'Qualité et limites',y);doc.setFont('helvetica','normal');doc.setFontSize(9);doc.setTextColor(...PDF_COLORS.ink);const quality=[`Observations valides : ${valid}. Observations incomplètes ou exclues : ${incomplete}.`,'Les commandes externes et B2B sont exclues par défaut de l’analyse rayon.','Une vente totale signale une rupture probable ; elle ne prouve pas une demande non servie.','Les recommandations restent des aides à la décision et nécessitent une validation humaine.'];quality.forEach(line=>{doc.text(doc.splitTextToSize(`• ${line}`,pageW-PDF_MARGIN*2),PDF_MARGIN,y);y+=10;});y=ensurePageSpace(doc,y,55);y=addSectionTitle(doc,'Méthodologie',y);['Ventes réelles = quantité reçue − déchets.','Taux de vente = total vendu ÷ total reçu. Taux de déchets = total déchets ÷ total reçu.','Les recommandations utilisent les occurrences du même jour de semaine et le mapping vendredi production → samedi vente.','La confiance combine occurrences, volume, complétude et stabilité. Elle reste faible sous quatre occurrences.','Un retrait recommandé exige au moins huit occurrences, huit semaines, deux sous-périodes faibles, une confiance élevée et aucune anomalie explicative.'].forEach(line=>{doc.text(doc.splitTextToSize(`• ${line}`,pageW-PDF_MARGIN*2),PDF_MARGIN,y);y+=10;});
  addDocumentFooters(doc,{documentName:'Aide à la décision',period:period(ctx),generatedAt:generated});return{doc,filename:safePdfFilename(['KKOPS','Aide-decision',ctx.scope,ctx.periodStart,ctx.periodEnd])};
};

export interface DeliveryPdfData {storeName:string;productionDate:string;deliveryDate:string;sourceLabel:string;reference?:string;comments?:string;items:Array<{name:string;conditioning?:string;planned:number;received:number|null;waste:number|null}>;boxes:Array<{name:string;planned:number;received:number|null;waste:number|null}>}
export const buildDeliveryPdf=(data:DeliveryPdfData,logo?:string|null)=>{const doc=createPdf('portrait',{title:`Bon de livraison — ${data.storeName}`,subject:'Contrôle de livraison'});let y=addDocumentHeader(doc,{title:'Bon de livraison',subtitle:data.sourceLabel,period:data.deliveryDate,scope:data.storeName,logo});const info=[['Date de production',data.productionDate],['Date de livraison',data.deliveryDate],['Magasin',data.storeName],...(data.reference?[['Référence',data.reference]]:[])];addDataTable(doc,{y,head:[['Informations du document','Valeur']],body:info});y=(doc as any).lastAutoTable.finalY+10;y=addSectionTitle(doc,'Doughnuts individuels',y);y=data.items.length?addDataTable(doc,{y,head:[['Produit','Conditionnement','Prévu','Reçu','Déchets']],body:data.items.map(i=>[i.name,i.conditioning||'—',i.planned,formatPdfNumber(i.received),formatPdfNumber(i.waste)]),columnStyles:{2:{halign:'right'},3:{halign:'right'},4:{halign:'right'}}}):addEmptyMessage(doc,'Aucun doughnut individuel.',y);if(data.boxes.length){y=ensurePageSpace(doc,y+9,35,()=>addDocumentHeader(doc,{title:'Bon de livraison — suite',period:data.deliveryDate,scope:data.storeName,logo}));y=addSectionTitle(doc,'Boîtes',y+8);y=addDataTable(doc,{y,head:[['Boîte','Prévu','Reçu','Déchets']],body:data.boxes.map(b=>[b.name,b.planned,formatPdfNumber(b.received),formatPdfNumber(b.waste)]),columnStyles:{1:{halign:'right'},2:{halign:'right'},3:{halign:'right'}}});}y=ensurePageSpace(doc,y+8,40);doc.setFontSize(8);doc.setTextColor(...PDF_COLORS.muted);if(data.comments){doc.text(doc.splitTextToSize(`Commentaire : ${data.comments}`,170),PDF_MARGIN,y);y+=15;}doc.setDrawColor(...PDF_COLORS.line);doc.line(PDF_MARGIN,y+10,90,y+10);doc.line(110,y+10,195,y+10);doc.text('Contrôle logistique',PDF_MARGIN,y+16);doc.text('Réception magasin',110,y+16);addDocumentFooters(doc,{documentName:'Bon de livraison',period:data.deliveryDate});return{doc,filename:safePdfFilename(['KKOPS','Bon-livraison',data.storeName,data.deliveryDate])};};

export interface ProductionPlanPdfData {date:string;stores:Array<{name:string;deliveryDate:string;items:Array<{name:string;form:string;quantity:number}>;boxes:Array<{name:string;quantity:number;size:number|null}>}>}
export const buildProductionPlanPdf=(data:ProductionPlanPdfData,logo?:string|null)=>{const doc=createPdf('landscape',{title:`Plan de production — ${data.date}`,subject:'Instructions de production par magasin'});let y=addDocumentHeader(doc,{title:'Plan de production',subtitle:'Volumes à préparer par point de vente',period:data.date,scope:`${data.stores.length} magasin(s)`,logo});const total=data.stores.reduce((s,store)=>s+store.items.reduce((a,i)=>a+i.quantity,0)+store.boxes.reduce((a,b)=>a+b.quantity*(b.size||0),0),0);addKpiCard(doc,{x:PDF_MARGIN,y,width:60,label:'ÉQUIVALENT DOUGHNUTS TOTAL',value:formatPdfNumber(total)});addKpiCard(doc,{x:PDF_MARGIN+64,y,width:60,label:'MAGASINS',value:String(data.stores.length)});y+=34;for(const store of data.stores){y=ensurePageSpace(doc,y,55,()=>addDocumentHeader(doc,{title:'Plan de production — suite',period:data.date,scope:store.name,logo}));y=addSectionTitle(doc,store.name,y,`Livraison ${store.deliveryDate}`);if(store.items.length)y=addDataTable(doc,{y,head:[['Variété','Forme','Quantité sans réserve','Forme avec réserve 5 %']],body:store.items.map(i=>[i.name,i.form,i.quantity,Math.ceil(i.quantity*1.05)]),columnStyles:{2:{halign:'right'},3:{halign:'right'}}});if(store.boxes.length){y=ensurePageSpace(doc,y+7,30);y=addSectionTitle(doc,'Boîtes',y+7);y=addDataTable(doc,{y,head:[['Configuration','Nombre de boîtes','Taille','Équivalent doughnuts']],body:store.boxes.map(b=>[b.name,b.quantity,b.size==null?'Donnée inconnue':b.size,b.size==null?'Donnée inconnue':b.quantity*b.size]),columnStyles:{1:{halign:'right'},2:{halign:'right'},3:{halign:'right'}}});}y+=9;}addDocumentFooters(doc,{documentName:'Plan de production',period:data.date});return{doc,filename:safePdfFilename(['KKOPS','Plan-production',data.date])};};
