import React,{useEffect,useMemo,useState} from 'react';
import {AlertTriangle,Download,PackageSearch,RefreshCw,Search} from 'lucide-react';
import {Bar,BarChart,CartesianGrid,Legend,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {normalizeProductionPlans} from '../analytics/engine';
import {articleRows,articleSeries,articleTotals,comparisonChange,type ArticleRow} from '../analytics/articleAnalysis';
import {addDays,parseIsoDate,toIsoDate} from '../analytics/salesDate';
import type {ProductType} from '../analytics/types';
import {articleAnalysisService,type ArticleOption} from '../services/articleAnalysisService';
import {buildArticlePdf} from '../pdf/reports';
import {loadPdfImage} from '../pdf/pdfKit';
import logo from '../assets/digital_72_png-KK_logo_Red_Green_FNL.png';

type Period='day'|'week'|'month'|'year'|'range';
const fmt=(n:number|null,percent=false)=>n===null?'Non renseigné':percent?new Intl.NumberFormat('fr-CH',{style:'percent',maximumFractionDigits:1}).format(n):new Intl.NumberFormat('fr-CH').format(n);
const today=()=>new Date().toISOString().slice(0,10);
const windowFor=(period:Period,anchor:string,start:string,end:string)=>{const d=parseIsoDate(anchor);if(period==='day')return{start:anchor,end:anchor};if(period==='week'){const day=(d.getUTCDay()+6)%7,s=toIsoDate(new Date(d.getTime()-day*86400000));return{start:s,end:addDays(s,6)}}if(period==='month'){const y=d.getUTCFullYear(),m=d.getUTCMonth();return{start:`${y}-${String(m+1).padStart(2,'0')}-01`,end:toIsoDate(new Date(Date.UTC(y,m+1,0,12)))}}if(period==='year')return{start:`${d.getUTCFullYear()}-01-01`,end:`${d.getUTCFullYear()}-12-31`};return{start,end}};

export default function ArticleAnalysis({stores,varieties,boxes}:{stores:any[];varieties:any[];boxes:any[]}){
  const saved=()=>{try{return JSON.parse(localStorage.getItem('kkops.article-analysis')||'{}')}catch{return{}}};const initial=saved();
  const [period,setPeriod]=useState<Period>(initial.period||'month'),[anchor,setAnchor]=useState(initial.anchor||today()),[start,setStart]=useState(initial.start||addDays(today(),-30)),[end,setEnd]=useState(initial.end||today());
  const [selected,setSelected]=useState<ArticleOption|null>(initial.selected||null),[storeIds,setStoreIds]=useState<string[]>(initial.storeIds||[]),[query,setQuery]=useState(''),[options,setOptions]=useState<ArticleOption[]>([]);
  const [rows,setRows]=useState<ArticleRow[]>([]),[previousRows,setPreviousRows]=useState<ArticleRow[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState<string|null>(null),[page,setPage]=useState(1),[incompleteOnly,setIncompleteOnly]=useState(false),[sort,setSort]=useState<'productionDate'|'salesDate'|'storeName'>('salesDate');
  const window=useMemo(()=>windowFor(period,anchor,start,end),[period,anchor,start,end]),days=Math.round((parseIsoDate(window.end).getTime()-parseIsoDate(window.start).getTime())/86400000)+1,previous={start:addDays(window.start,-days),end:addDays(window.end,-days)};
  useEffect(()=>{localStorage.setItem('kkops.article-analysis',JSON.stringify({period,anchor,start,end,selected,storeIds}))},[period,anchor,start,end,selected,storeIds]);
  useEffect(()=>{if(query.trim().length<2){setOptions([]);return}const term=query.toLocaleLowerCase('fr');const local:ArticleOption[]=[...varieties.map(v=>({id:v.id,name:v.name,type:'variety' as const})),...boxes.map(b=>({id:b.id,name:b.name,type:'box' as const}))].filter(o=>o.name.toLocaleLowerCase('fr').includes(term));const timer=setTimeout(()=>articleAnalysisService.search(query).then(historical=>setOptions([...new Map([...local,...historical].map(o=>[`${o.type}:${o.id}`,o])).values()].slice(0,30))).catch(()=>setOptions(local.slice(0,30))),250);return()=>clearTimeout(timer)},[query,varieties,boxes]);
  const load=async()=>{if(!selected)return;setLoading(true);setError(null);try{const [current,prior]=await Promise.all([articleAnalysisService.load({productType:selected.type,productId:selected.id,startDate:addDays(window.start,-1),endDate:window.end,storeIds}),articleAnalysisService.load({productType:selected.type,productId:selected.id,startDate:addDays(previous.start,-1),endDate:previous.end,storeIds})]);const normalize=(plans:any[])=>articleRows(normalizeProductionPlans(plans),selected.type,selected.id,storeIds);setRows(normalize(current.plans).filter(r=>r.salesDate>=window.start&&r.salesDate<=window.end));setPreviousRows(normalize(prior.plans).filter(r=>r.salesDate>=previous.start&&r.salesDate<=previous.end));setPage(1)}catch(e){setError(e instanceof Error?e.message:'Chargement impossible')}finally{setLoading(false)}};
  useEffect(()=>{load()},[selected?.type,selected?.id,window.start,window.end,storeIds.join('|')]);
  const totals=useMemo(()=>articleTotals(rows),[rows]),priorTotals=useMemo(()=>articleTotals(previousRows),[previousRows]),granularity=period==='year'?'month':period==='month'||period==='range'&&days>31?'week':'day',series=useMemo(()=>articleSeries(rows,granularity),[rows,granularity]);
  const visibleRows=useMemo(()=>incompleteOnly?rows.filter(row=>row.status!=='Complet'):rows,[rows,incompleteOnly]),sorted=useMemo(()=>[...visibleRows].sort((a,b)=>String(a[sort]).localeCompare(String(b[sort]))),[visibleRows,sort]),pageRows=sorted.slice((page-1)*20,page*20),pages=Math.max(1,Math.ceil(visibleRows.length/20));
  const card=(label:string,value:number|null,previousValue:number|null,knownLines=totals.coverage.totalLines,percent=false)=>{const change=comparisonChange(value,previousValue),partial=value!==null&&knownLines<totals.coverage.totalLines,detail=knownLines===totals.coverage.totalLines?`Données complètes : ${knownLines} ligne${knownLines>1?'s':''}`:`${knownLines} ligne${knownLines>1?'s':''} renseignée${knownLines>1?'s':''} sur ${totals.coverage.totalLines}`;return <div className="article-kpi" title={partial?`${totals.coverage.incompleteDays} journée(s) incomplète(s). Réceptions manquantes : ${totals.coverage.missingReceptionStores.join(', ')||'aucune'}. Déchets manquants : ${totals.coverage.missingWasteStores.join(', ')||'aucun'}.`:detail}><span>{label}</span><strong>{fmt(value,percent)}</strong>{partial&&<small className="partial">Partiellement renseigné · {detail}</small>}{!partial&&value!==null&&<small>{detail}</small>}{change&&<small className={change.quantity>0?'up':change.quantity<0?'down':''}>{change.quantity>0?'+':''}{fmt(change.quantity)} · {change.percent===null?'—':fmt(change.percent,true)} vs période précédente</small>}</div>};
  const exportPdf=async()=>{if(!selected||!rows.length)return;const image=await loadPdfImage(logo),scope=storeIds.length?stores.filter(s=>storeIds.includes(s.id)).map(s=>s.name).join(', '):'Tous les magasins',reportRows=[...rows].sort((a,b)=>a.salesDate.localeCompare(b.salesDate));const out=buildArticlePdf({rows:reportRows,series,totals,article:selected.name,type:selected.type==='box'?'Boîte':'Doughnut individuel'},{periodStart:window.start,periodEnd:window.end,scope,logo:image,generatedAt:new Date()});out.doc.save(out.filename)};
  return <section className="article-analysis analytics-panel" aria-labelledby="article-title"><header><div><p className="stats-hero__eyebrow"><PackageSearch/> Analyse détaillée</p><h2 id="article-title">Analyse par article</h2><p>Une lecture traçable par identifiant, sans confondre variétés et boîtes.</p></div><button onClick={exportPdf} disabled={!rows.length||loading} className="article-export"><Download/> Télécharger le rapport article en PDF</button></header>
    <div className="article-filters"><label><span>Article</span><div className="article-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={selected?selected.name:'Rechercher une variété ou une boîte…'}/></div>{options.length>0&&<div className="article-options">{(['variety','box'] as ProductType[]).map(type=><div key={type}><b>{type==='variety'?'Doughnuts individuels / variétés':'Boîtes'}</b>{options.filter(o=>o.type===type).map(o=><button key={`${o.type}:${o.id}`} onClick={()=>{setSelected(o);setQuery('');setOptions([])}}>{o.name}{o.historical&&<small>Historique</small>}</button>)}</div>)}</div>}{selected&&<em>{selected.type==='box'?'Boîte':'Variété'} · ID {selected.id}</em>}</label>
      <label><span>Période</span><select value={period} onChange={e=>setPeriod(e.target.value as Period)}><option value="day">Jour</option><option value="week">Semaine</option><option value="month">Mois</option><option value="year">Année</option><option value="range">Personnalisée</option></select>{period==='range'?<div className="article-dates"><input type="date" value={start} onChange={e=>setStart(e.target.value)}/><input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></div>:<input type="date" value={anchor} onChange={e=>setAnchor(e.target.value)}/>}</label>
      <fieldset><legend>Magasins</legend><label className="check"><input type="checkbox" checked={!storeIds.length} onChange={()=>setStoreIds([])}/> Tous les magasins</label><div className="article-store-list">{stores.map(store=><label className="check" key={store.id}><input type="checkbox" checked={storeIds.includes(store.id)} onChange={()=>setStoreIds(ids=>ids.includes(store.id)?ids.filter(id=>id!==store.id):[...ids,store.id])}/>{store.name}</label>)}</div></fieldset></div>
    {!selected?<div className="article-empty"><PackageSearch/><b>Sélectionnez un article</b><span>Les données seront demandées uniquement pour cet identifiant et ce périmètre.</span></div>:loading?<div className="article-empty"><RefreshCw className="spin"/><b>Chargement de l’analyse complète…</b></div>:error?<div className="article-error"><AlertTriangle/><span>{error}</span><button onClick={load}>Réessayer</button></div>:<>
      <div className="article-kpis">{card('Total prévu / produit',totals.planned,priorTotals.planned)}{card('Total réceptionné',totals.received,priorTotals.received,totals.coverage.receivedKnownLines)}{card('Total déchets',totals.waste,priorTotals.waste,totals.coverage.wasteKnownLines)}{card('Total vendu',totals.sold,priorTotals.sold,totals.coverage.soldKnownLines)}{card('Taux moyen de déchets',totals.wasteRate,priorTotals.wasteRate,totals.coverage.completeLines,true)}{card('Écart production / réception',totals.receptionGap,priorTotals.receptionGap,totals.coverage.receivedKnownLines)}</div>
      {rows.length?<><div className="article-chart"><h3>Production, réception, ventes et déchets</h3><ResponsiveContainer width="100%" height={330}><BarChart data={series}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="label"/><YAxis/><Tooltip formatter={(value:any,name:any,item:any)=>[value===null?'Non renseigné':fmt(value),`${name}${item?.payload?.coverage?.partial?' (partiel)':''}`]}/><Legend/><Bar dataKey="planned" name="Production / prévision" fill="#00854a"/><Bar dataKey="received" name="Réception" fill="#3679b8"/><Bar dataKey="sold" name="Ventes" fill="#66a844"/><Bar dataKey="waste" name="Déchets" fill="#d33d56"/></BarChart></ResponsiveContainer></div>
      <div className="article-table-wrap"><div className="article-table-head"><h3>Détail ({visibleRows.length})</h3><div className="article-table-actions"><label className="check"><input type="checkbox" checked={incompleteOnly} onChange={e=>{setIncompleteOnly(e.target.checked);setPage(1)}}/> Afficher uniquement les données incomplètes</label><label>Trier par <select value={sort} onChange={e=>setSort(e.target.value as any)}><option value="salesDate">Date de vente</option><option value="productionDate">Date de production</option><option value="storeName">Magasin</option></select></label></div></div><table><thead><tr><th>Production</th><th>Livraison / vente</th><th>Magasin</th><th>Article</th><th>Prévu</th><th>Reçu</th><th>Déchets</th><th>Vendu</th><th>Taux</th><th>Complétude</th></tr></thead><tbody>{pageRows.map(row=><tr key={row.id} className={row.status==='Donnée incohérente'?'anomaly':''}><td>{row.productionDate}</td><td>{row.salesDate}</td><td>{row.storeName}</td><td>{row.productName}</td><td>{fmt(row.planned)}</td><td>{fmt(row.receivedKnown?row.received:null)}</td><td>{fmt(row.wasteKnown?row.waste:null)}</td><td>{fmt(row.sold)}</td><td>{row.status==='Complet'&&row.received!==null&&row.received>0?fmt(row.waste!/row.received,true):'Non renseigné'}</td><td><span className={`article-status status-${row.status.toLowerCase().replaceAll(' ','-')}`}>{row.status}</span>{row.planned===0&&row.receivedKnown&&row.received!>0&&<small>Réception non prévue</small>}</td></tr>)}</tbody></table><div className="article-pagination"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Précédent</button><span>Page {page} / {pages}</span><button disabled={page===pages} onClick={()=>setPage(p=>p+1)}>Suivant</button></div></div></>:<div className="article-empty"><PackageSearch/><b>Aucune donnée disponible pour ces filtres</b></div>}</>}
  </section>;
}
