import React, { useMemo, useState } from 'react';
import { AlertTriangle, ArrowDown, ArrowUp, ChevronRight, CheckCircle, Eye, FlaskConical, Minus, ShieldCheck, X } from 'lucide-react';
import type { ProductMetrics, RecommendationStatus } from '../analytics/types';

const statusStyle: Record<RecommendationStatus, { icon: React.ElementType; className: string }> = {
  'À tester': { icon: FlaskConical, className: 'bg-blue-50 text-blue-800 border-blue-200' },
  'À surveiller': { icon: Eye, className: 'bg-amber-50 text-amber-900 border-amber-200' },
  'À augmenter': { icon: ArrowUp, className: 'bg-emerald-50 text-emerald-800 border-emerald-200' },
  'À maintenir': { icon: CheckCircle, className: 'bg-gray-50 text-gray-800 border-gray-200' },
  'À réduire': { icon: ArrowDown, className: 'bg-orange-50 text-orange-900 border-orange-200' },
  'Candidat au retrait': { icon: AlertTriangle, className: 'bg-red-50 text-red-800 border-red-200' },
  'Retrait recommandé': { icon: AlertTriangle, className: 'bg-red-100 text-red-950 border-red-300' },
};
const order: Record<RecommendationStatus, number> = { 'Retrait recommandé':0,'Candidat au retrait':1,'À réduire':2,'À augmenter':3,'À surveiller':4,'À tester':5,'À maintenir':6 };
const pct=(v:number)=>`${Math.round(v*100)} %`;

function Badge({ status }: { status: RecommendationStatus }) { const cfg=statusStyle[status], Icon=cfg.icon; return <span className={`inline-flex items-center gap-1 rounded-full border px-2 py-1 text-xs font-semibold ${cfg.className}`}><Icon size={14}/>{status}</span>; }

export default function StoreAnalyticsView({ metrics, stores }: { metrics: ProductMetrics[]; stores: Array<{id:string;name:string}> }) {
  const [storeId,setStoreId]=useState(stores[0]?.id || ''); const [query,setQuery]=useState(''); const [type,setType]=useState('all'); const [status,setStatus]=useState('all'); const [confidence,setConfidence]=useState('all'); const [quality,setQuality]=useState('all'); const [sort,setSort]=useState('priority'); const [detail,setDetail]=useState<ProductMetrics|null>(null);
  React.useEffect(()=>{ if(!stores.some(s=>s.id===storeId)) setStoreId(stores[0]?.id || ''); },[stores,storeId]);
  const rows=useMemo(()=>metrics.filter(m=>m.storeId===storeId && m.productName.toLowerCase().includes(query.toLowerCase()) && (type==='all'||m.productType===type) && (status==='all'||m.status===status) && (confidence==='all'||m.confidenceLevel===confidence) && (quality==='all'||(quality==='complete'?m.incompleteCount+m.invalidCount===0:m.incompleteCount+m.invalidCount>0))).sort((a,b)=>sort==='waste'?b.wasteRate-a.wasteRate:sort==='sales'?a.salesRate-b.salesRate:order[a.status]-order[b.status]),[metrics,storeId,query,type,status,confidence,quality,sort]);
  return <section className="analytics-panel mt-8" aria-labelledby="store-analysis-title">
    <div className="border-b border-gray-200 p-5 sm:p-6"><p className="text-xs font-bold uppercase tracking-wider text-krispy-green">Aide à la décision</p><h2 id="store-analysis-title" className="mt-1 text-2xl font-bold text-gray-900">Par magasin</h2><p className="mt-1 text-sm text-gray-600">Seules les livraisons rayon confirmées et dont les déchets sont finalisés alimentent les recommandations.</p></div>
    <div className="grid gap-3 border-b bg-gray-50 p-4 sm:grid-cols-2 lg:grid-cols-4">
      <label className="text-xs font-semibold text-gray-700">Point de vente<select aria-label="Point de vente" value={storeId} onChange={e=>setStoreId(e.target.value)} className="mt-1 w-full rounded-lg border-gray-300 text-sm">{stores.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label>
      <label className="text-xs font-semibold text-gray-700">Produit<input aria-label="Rechercher un produit" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher…" className="mt-1 w-full rounded-lg border-gray-300 text-sm"/></label>
      <label className="text-xs font-semibold text-gray-700">Type<select value={type} onChange={e=>setType(e.target.value)} className="mt-1 w-full rounded-lg border-gray-300 text-sm"><option value="all">Tous</option><option value="variety">Individuel</option><option value="box">Boîte</option></select></label>
      <label className="text-xs font-semibold text-gray-700">Statut<select value={status} onChange={e=>setStatus(e.target.value)} className="mt-1 w-full rounded-lg border-gray-300 text-sm"><option value="all">Tous</option>{Object.keys(statusStyle).map(s=><option key={s}>{s}</option>)}</select></label>
      <label className="text-xs font-semibold text-gray-700">Confiance<select value={confidence} onChange={e=>setConfidence(e.target.value)} className="mt-1 w-full rounded-lg border-gray-300 text-sm"><option value="all">Toutes</option><option>Faible</option><option>Moyen</option><option>Élevé</option></select></label>
      <label className="text-xs font-semibold text-gray-700">Qualité<select value={quality} onChange={e=>setQuality(e.target.value)} className="mt-1 w-full rounded-lg border-gray-300 text-sm"><option value="all">Toutes</option><option value="complete">Complète</option><option value="issues">À contrôler</option></select></label>
      <label className="text-xs font-semibold text-gray-700">Trier par<select value={sort} onChange={e=>setSort(e.target.value)} className="mt-1 w-full rounded-lg border-gray-300 text-sm"><option value="priority">Actions prioritaires</option><option value="waste">Plus gros déchets</option><option value="sales">Plus faible taux de vente</option></select></label>
    </div>
    {!storeId ? <div className="p-10 text-center text-gray-500">Aucun point de vente accessible.</div> : rows.length===0 ? <div className="p-10 text-center"><AlertTriangle className="mx-auto text-amber-500"/><h3 className="mt-2 font-semibold">Aucun résultat</h3><p className="text-sm text-gray-500">Aucun produit proposé ou aucune observation ne correspond aux filtres.</p></div> : <>
      <div className="hidden overflow-x-auto lg:block"><table className="min-w-full text-sm"><thead className="bg-gray-50 text-left text-xs uppercase text-gray-500"><tr>{['Produit','Statut','Reçu','Vendu','Déchets','Taux vente','Taux déchets','Ruptures','Tendance','Actuel','Recommandé','Confiance',''].map(h=><th className="whitespace-nowrap px-3 py-3" key={h}>{h}</th>)}</tr></thead><tbody className="divide-y">{rows.map(m=><tr key={m.key} className="hover:bg-gray-50"><td className="px-3 py-3 font-semibold">{m.productName}<span className="block text-xs font-normal text-gray-500">{m.productType==='box'?'Boîte':'Individuel'}</span></td><td className="px-3"><Badge status={m.status}/></td><td className="px-3">{m.received}</td><td className="px-3 font-semibold text-emerald-700">{m.sold}</td><td className="px-3 text-red-700">{m.waste}</td><td className="px-3">{pct(m.salesRate)}</td><td className="px-3">{pct(m.wasteRate)}</td><td className="px-3">{m.probableStockouts}/{m.validCount}</td><td className="px-3">{m.trend===null?'—':`${m.trend>=0?'+':''}${pct(m.trend)}`}</td><td className="px-3">{m.referenceQuantity===null?'—':Math.round(m.referenceQuantity)}</td><td className="px-3 font-semibold">{m.recommendationLabel}</td><td className="px-3"><span className="whitespace-nowrap"><ShieldCheck size={14} className="mr-1 inline"/>{m.confidenceLevel} {m.confidenceScore}</span></td><td className="px-3"><button aria-label={`Voir le détail de ${m.productName}`} onClick={()=>setDetail(m)} className="rounded-lg p-2 text-krispy-green hover:bg-green-50"><ChevronRight/></button></td></tr>)}</tbody></table></div>
      <div className="grid gap-3 p-4 lg:hidden">{rows.map(m=><button key={m.key} onClick={()=>setDetail(m)} className="rounded-xl border bg-white p-4 text-left shadow-sm"><div className="flex items-start justify-between gap-2"><div><strong>{m.productName}</strong><span className="block text-xs text-gray-500">{m.productType==='box'?'Boîte':'Individuel'}</span></div><Badge status={m.status}/></div><div className="mt-4 grid grid-cols-3 gap-2 text-xs"><span>Déchets<strong className="block text-red-700">{pct(m.wasteRate)}</strong></span><span>Recommandation<strong className="block">{m.recommendationLabel}</strong></span><span>Confiance<strong className="block">{m.confidenceLevel} · {m.confidenceScore}</strong></span></div></button>)}</div>
    </>}
    {detail&&<div className="fixed inset-0 z-50 flex justify-end bg-black/35" role="dialog" aria-modal="true" aria-label={`Détail ${detail.productName}`}><button className="absolute inset-0" onClick={()=>setDetail(null)} aria-label="Fermer"/><aside className="relative h-full w-full max-w-xl overflow-y-auto bg-white p-5 shadow-2xl sm:p-7"><button onClick={()=>setDetail(null)} className="absolute right-4 top-4 rounded-lg p-2 hover:bg-gray-100" aria-label="Fermer le détail"><X/></button><p className="text-xs font-bold uppercase text-krispy-green">{detail.storeName} · {detail.productType==='box'?'Boîte':'Individuel'}</p><h3 className="mt-1 pr-10 text-2xl font-bold">{detail.productName}</h3><div className="mt-4"><Badge status={detail.status}/></div><div className="mt-5 rounded-xl bg-gray-50 p-4"><p className="text-sm text-gray-500">Quantité de référence → recommandation</p><p className="text-2xl font-bold">{detail.referenceQuantity===null?'—':Math.round(detail.referenceQuantity)} <Minus className="inline"/> {detail.recommendationLabel}</p></div><h4 className="mt-6 font-bold">Pourquoi ?</h4>{detail.reasons.map(r=><p key={r} className="mt-2 text-sm text-gray-700">{r}</p>)}<h4 className="mt-6 font-bold">Confiance : {detail.confidenceLevel} ({detail.confidenceScore}/100)</h4><ul className="mt-2 list-disc pl-5 text-sm text-gray-600">{detail.confidenceReasons.map(r=><li key={r}>{r}</li>)}</ul><h4 className="mt-6 font-bold">Historique et qualité</h4><p className="text-sm text-gray-600">{detail.validCount} valides · {detail.incompleteCount} incomplètes · {detail.excludedCount} exclues · {detail.invalidCount} anomalies</p><div className="mt-3 space-y-2">{detail.observations.map(o=><div key={o.id} className="rounded-lg border p-3 text-sm"><div className="flex justify-between"><strong>{o.salesDate}</strong><span>{o.quality==='valid'?'Valide':o.quality}</span></div><p>Reçu {o.received??'—'} · Vendu {o.sold??'—'} · Déchets {o.waste??'—'} {o.probableStockout?'· Rupture probable':''}</p>{o.issues.map(i=><p className="text-xs text-red-700" key={i}>{i}</p>)}</div>)}</div><h4 className="mt-6 font-bold">Seuils appliqués</h4><p className="text-sm text-gray-600">4 occurrences minimum · hausse après 3 ruptures probables sur ≥ 50 % des jours · déchets élevés &gt; 30 % · retrait définitif seulement avec 8 occurrences, 8 semaines et confiance élevée.</p></aside></div>}
  </section>;
}
